// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlcMPQz9mz4W3coO3ab5dpbVn3FNiNXRY',
    appId: '1:690291656518:web:45a0cd0294f36a3c310747',
    messagingSenderId: '690291656518',
    projectId: 'swifttasks-92062',
    authDomain: 'swifttasks-92062.firebaseapp.com',
    storageBucket: 'swifttasks-92062.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOEwupGiY4xtYIXZ9bZt69h97EbfeEWho',
    appId: '1:690291656518:android:a8c9796ab5b20806310747',
    messagingSenderId: '690291656518',
    projectId: 'swifttasks-92062',
    storageBucket: 'swifttasks-92062.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo_We9HYQMWSC3ofD_U3ZQCkds4Ea_-yY',
    appId: '1:690291656518:ios:fecd3a6feb1a3896310747',
    messagingSenderId: '690291656518',
    projectId: 'swifttasks-92062',
    storageBucket: 'swifttasks-92062.appspot.com',
    iosBundleId: 'com.example.swifttasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo_We9HYQMWSC3ofD_U3ZQCkds4Ea_-yY',
    appId: '1:690291656518:ios:d08991940033c8c9310747',
    messagingSenderId: '690291656518',
    projectId: 'swifttasks-92062',
    storageBucket: 'swifttasks-92062.appspot.com',
    iosBundleId: 'com.example.swifttasks.RunnerTests',
  );
}
